### PR TITLE
Add support for conditional scaffolding

### PR DESCRIPTION
**Pull request by boma96**
Following options are added to the toolkit:

- -n, --name (Specifies names of the tasks and workflows to scaffold)
- -a, --app (Specifies owner apps of the tasks and workflows to scaffold)
- -e, --email (Specifies owner emails of the tasks and workflows to scaffold)
- --no-tasks (Skip task scaffolding)
- --no-workflows (Skip workflow scaffolding)
- --dry-run (Print workflows and task which would be scaffolded if toolkit is ran without this option)

For name, app, and email filters multiple values can be specified e.g. -n A_% B_%. (This performs scaffolding of all tasks and wf which have A_ and B_ prefixes)
Name filter supports special character % which matches zero or more characters

When multiple filters of different types are present then AND operation is applied i.e. all filters must be satisfied in order for it to be scaffolded.

### CODE REVIEW

**Review by ognjenkatic — COMMENTED** [review]
LGTM, but I cannot see where we are setting the value of the dryrun option? Did i miss something ?

**Comment by boma96** [comment]
> LGTM, but I cannot see where we are setting the value of the dryrun option? Did i miss something ?

Forgot about this, will implement

**Comment by boma96** [comment]
@ognjenkatic Dry run option is implemented, check PR description

**Comment by ognjenkatic** [comment]
> @ognjenkatic Dry run option is implemented, check PR description

Looks good now, merging.

**Pull request merged**
